# Local (Docker container) PostgreSQL (not a Testcontainer)
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql:postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ----- memory related configurations -----

# true if we should use the in-memory repositories, otherwise the Spring Data JDBC ones are used
nimnamfood.data.inmemory=false

# true if we should run migration scripts (disable when using memory repos)
spring.flyway.enabled=true

# comment if we should use jdbc repos
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# uncomment for sql logs
# logging.level.org.springframework.jdbc.core=TRACE
# uncomment for transactions logs
# logging.level.org.springframework.transaction.interceptor=TRACE