spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver

# ----- memory related configurations -----

# true if we should run migration scripts (disable when using memory repos)
spring.flyway.enabled=true